import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


// import { 
//   AppBar, Box, Toolbar, Typography, Button, IconButton, Container
// } from '@mui/material';
// import MenuIcon from '@mui/icons-material/Menu';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
